# Generated by Django 3.1.4 on 2020-12-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answercount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('intent', models.CharField(blank=True, max_length=50, null=True)),
                ('answer', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ANSWER_COUNT',
            },
        ),
    ]
